### ISSUE TITLE
A better/more positive name

### ISSUE THREAD

**Issue by TanklesXL** [bcpeinhardt/code_review#12]
Whinge is quirky but has too negative a meaning, let's pick something positive!!!

**Comment by bcpeinhardt** [comment]
> gleam-review? 😄

If you feel comfortable associating it with elm-review then I'm for it. I much prefer simple clear names to quirky ones (and gleam-review is quite clear).

**Comment by jfmengels** [comment]
If it follows most of the same philosophies, then I'm all for it :smile:

**Comment by giacomocavalieri** [comment]
Packages can't start with gleam though the build tool will refuse to publish it

**Comment by bcpeinhardt** [comment]
Ah yeah I forgot. For the record there's not package called linter, lint, or review on hexdocs haha. We could have `gleam run -m lint`.
Also litmus could be a good name.

**Comment by bcpeinhardt** [comment]
We settled on code_review outside this chat
