### ISSUE TITLE
Decide how the user is going to customise and run the linter in their project

### ISSUE THREAD

**Issue by lpil** [bcpeinhardt/code_review#24]
Just making note of discussion on discord

https://discord.com/channels/768594524158427167/1227343790893957190/1230628128171233360

**Comment by TanklesXL** [comment]
gonna brain-dump here what my current ideas are on the subject:

1) code_review module exports something like a (note the following is an example and the type names are probably not accurate. This module could potentially also expose a list of the most valuable lints (ideally all the ones included in the library)

```gleam
fn run( lints: List(Lint)) -> Nil {...}

pub const default_lints: List(Lint) = [...]
```

2) the user can have an internal module called `lint` or whatever they want to call it, which contains a `main` that creates a list of lints to provide to `code_review.run`
```gleam
import code_review
import some_package
import some_other_package
...

pub fn main() {
  [
     some_package.lint,
     some_other_package.lint,
     ...
     ..code_review.default_lints
  ] |> code_review.run
}

**Comment by bcpeinhardt** [comment]
I like this in general. I think we shouldn't provide a `default_lints` list though. Because then we'll end up with people have to remove some of the lints haha.
Better to just a provide a snippet they can copy and paste.

**Comment by bcpeinhardt** [comment]
We've added a `gleam run -m code_review/setup` to generate the setup so I'm gonna close this :)
