### ISSUE TITLE
Lint: No `let assert`

### ISSUE THREAD

**Issue by inoas** [bcpeinhardt/code_review#27]
**What the rule should do:**

Similar to panic linting rule.

**What problems does it solve:**

Not crash during runtime?

**Example of things the rule would report:**

```gleam

`let assert` Ok(1) = some_fun_call()

```

**Example of things the rule would not report:**

```gleam

just `assert`.

```

**When to enable this rule:**

- As a quality/safty feature of gleam libraries.

**When (not) to enable this rule:**

- For gleam applications you control.
- For values constructed at runtime that are safe to construct such as colors from hex codes within 0-255 range.

**I am looking for:**

- Feedback
- Tips and help on how to implement it
- Someone to implement it with/for me, if I don't know how to

**Comment by giacomocavalieri** [comment]
I don't think this would be a good rule, it makes a lot of sense to use `let assert` in some places and disabling it as a whole would be really frustrating
